### ISSUE TITLE
Is it possible to obtain the vertex elimination order when a tree decomposition is given as an input?

### ISSUE THREAD

**Issue by jmeintrup** [mabseher/htd#9]
Question in the title.
I would like construct the vertex elimination order when giving a graph G and a tree decomposition TD of G as input.

I could not find much about this, since generally only the reverse (input: ordering, output TD) is needed.

Is this possible somehow using htd?

**Comment by daajoe** [comment]
Are you already using htd?
If not and high performance is not so much of an issue, you might want to take a look at
https://github.com/daajoe/htd_validate/blob/master/htd_validate/decompositions/decomposition.py
function _from_ordering, which does the opposite and implement it yourself.

If performance is an issue check look for
htd::BucketEliminationTreeDecompositionAlgorithm::computeDecomposition and reverse it, depending on your needs.
Not sure whether htd gives you this out of the box.

**Comment by jmeintrup** [comment]
Hello, thanks for your prompt answer.
I am not currently using htd, but was planning to.
I probably don't need high performance for the conversion step, so your python repo will be a good starting point. thanks!
Kind Regards
